### ISSUE TITLE
isLoggingIn never true

### ISSUE THREAD

**Issue by GrahamS-Quartech** [bcgov/citz-imb-sso-react#59]
I'm testing out this new property and it never seems to be in the true state. I would expect it to be true until the isAuthenticated goes from false to true or if some failure occurs. I think this behavior may be improved by simply setting the initialState to have isLoggingIn as true, but not entirely sure.

**Comment by BradyMitch** [comment]
Thanks I'll look into this. I know it is true before the user is redirected to the login page, but not after they get redirected back because the state gets reset. Setting by initialState might be the answer.

**Comment by BradyMitch** [comment]
On second thought this may not be the best option because that would act the same way as `isAuthenticated`. Maybe we just set it on page load after the user is redirected back after login and the `refresh_expires_in` query param is set in the file `src\components\Wrapper.tsx`

**Comment by BradyMitch** [comment]
This will be partially fixed in https://github.com/bcgov/citz-imb-sso-react/pull/78
After the user returns from the sso login page, for a split second it will be false but then it fill become true

Once merged and released this will part of version `1.0.0-alpha7`

**Comment by BradyMitch** [comment]
Closing as this is addressed in version `1.0.0-alpha7`
