### ISSUE TITLE
Bug: Automatic token refresh sometimes returns null

### ISSUE THREAD

**Issue by GrahamS-Quartech** [bcgov/citz-imb-sso-react#60]
It seems that sometimes the token refresh is silently failing despite returning a 200 status code. The response body is null, and as a result any subsequent calls relying on a valid keycloak authorization header suddenly fail.

**Comment by BradyMitch** [comment]
Closing as this was related to an older version. If the issue persists, please open a new ticket with the "Bug report" template.
